/* Data types */

CREATE OR REPLACE FUNCTION san_in(cstring)
  RETURNS SAN
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE
  AS 'MODULE_PATHNAME';

CREATE OR REPLACE FUNCTION san_out(SAN)
  RETURNS cstring
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE
  AS 'MODULE_PATHNAME';

CREATE OR REPLACE FUNCTION fen_in(cstring)
  RETURNS FEN
  AS 'MODULE_PATHNAME'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION fen_out(FEN)
  RETURNS cstring
  AS 'MODULE_PATHNAME'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE TYPE SAN (
  internallength = 1000,
  input          = san_in,
  output         = san_out
);

CREATE TYPE FEN (
  internallength = 128,
  input = fen_in,
  output = fen_out,
  alignment = double
);

/* Functions */

CREATE FUNCTION get_FirstMoves(SAN, integer)
  RETURNS SAN
  AS 'MODULE_PATHNAME', 'get_FirstMoves'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION has_opening(SAN, SAN)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'has_opening'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION get_board_state(SAN, integer)
  RETURNS FEN
  AS 'MODULE_PATHNAME', 'get_board_state'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION has_Board(SAN, FEN, integer)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'has_Board'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;


CREATE OR REPLACE FUNCTION san_eq(SAN, SAN)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'san_eq'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION san_lt(SAN, SAN)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'san_lt'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION san_gt(SAN, SAN)
  RETURNS boolean
  AS 'MODULE_PATHNAME', 'san_gt'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION san_cmp(SAN, SAN)
  RETURNS integer
  AS 'MODULE_PATHNAME', 'san_cmp'
  LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION san_like(SAN, TEXT) 
  RETURNS BOOLEAN
  AS 'MODULE_PATHNAME', 'san_like'
  LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION san_not_like(SAN, TEXT) 
  RETURNS BOOLEAN 
  AS 'MODULE_PATHNAME', 'san_not_like' 
  LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

/* Operators */

CREATE OPERATOR = (
  LEFTARG = SAN, RIGHTARG = SAN,
  PROCEDURE = san_eq,
  COMMUTATOR = =, NEGATOR = <>
);

CREATE OPERATOR < (
  LEFTARG = SAN, RIGHTARG = SAN,
  PROCEDURE = san_lt,
  COMMUTATOR = >, NEGATOR = >=
);

CREATE OPERATOR > (
  LEFTARG = SAN, RIGHTARG = SAN,
  PROCEDURE = san_gt,
  COMMUTATOR = <, NEGATOR = <=
);

CREATE OPERATOR ~~ (
  LEFTARG = SAN,
  RIGHTARG = TEXT,
  PROCEDURE = san_like,
  COMMUTATOR = !~~
);

CREATE OPERATOR !~~ (
  LEFTARG = SAN,
  RIGHTARG = TEXT,
  PROCEDURE = san_not_like
);

/* BTree Index */

CREATE OPERATOR CLASS san_ops 
DEFAULT FOR TYPE san 
USING btree AS
    OPERATOR 1 <,
    OPERATOR 3 =,
    OPERATOR 5 >,
    FUNCTION 1 san_cmp(san, san);